### ISSUE TITLE
Reopen all submissions when a dictionary updated

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-clinical#199] opened 2019-10-22 20:34 UTC
For an active submission, when the dictionary is updated we need to check all active submissions 

An active submission can fall into one of 2 states:
- complies to new schema.  In this case, set it to open 

- does not comply to new schema, In this case, st to new state `sometingneeds to happen` and let them know to restart 
- the act of submission needs to record the dictionary versions. 

@christinayung to decide if we want to do this, or just clear all active submissions a the cheap solution

**Comment by blabadi** [comment] 2019-11-08 13:11
this is now a duplicate of icgc-argo/argo-clinical#234

**Closed** 2019-11-08 18:59 UTC
Labels: duplicate, grooming
